version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt:0.2.2
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]
  redis:
    image: "redis/redis-stack-server:latest"